### ISSUE TITLE
Upgrade to jQuery3

### ISSUE THREAD

**Issue by nickmarden** [GSA/search-gov#2]
Our jQuery implementations are currently a bit long in the tooth:
- The SAYT tool [uses jQuery 1.7.1](https://github.com/GSA/search-gov/blob/master/app/assets/javascripts/sayt_loader_libs.js)
- The SERP and admin tools use [jquery-rails 3.1.4](https://github.com/rails/jquery-rails/tree/v3.1.4), and therefore jQuery 1.11.1

It would be great if both of these uses were upgraded to the latest-and-greatest jQuery 3 without any loss of functionality *or* the introduction of any Javascript errors in the SERP pages of Search.gov customers who embed the SAYT library in their own pages.

**Comment by viclim** [comment]
I'm looking into this.
