### ISSUE TITLE
Changing a Collection's time scope should not send a searcher back to Page 1 results

### ISSUE THREAD

**Issue by nickmarden** [GSA/search-gov#30]
As a searcher,
When I change my Collections time scoping from the default "Any Time" to another time option,
I should not start seeing results from page 1.

Given that I'm on a Collection,
I should continue to see results only from within the Collection I was on
And the results should be filtered and sorted based on my specifications.

Background:
Reported by a customer on Feb 7 2018. The customer noticed that dc= was getting stripped away when she changed the time settings on the Consumer Information Collection of ftc_dev:

https://search.usa.gov/search/docs?affiliate=ftc_prod&dc=5047&query=amazon.com

---

Additional notes from @MothOnMars: 

The time filter links should be using the `/search/docs` route, instead of `/search`:
Example:

link is: https://search.usa.gov/search?affiliate=ftc_prod&query=amazon.com&sort_by=r&tbs=m
link should be: https://search.usa.gov/search/docs?affiliate=ftc_prod&dc=5047&query=amazon.com&sort_by=r&tbs=m

Unfortunately, even when the correct link is used, it appears that the time filter and sort parameters are not used. The same results are returned for the following two searches, whereas the second search should filter out any results older than a month :

https://search.usa.gov/search/docs?affiliate=ftc_prod&dc=5047&query=amazon.com
https://search.usa.gov/search/docs?affiliate=ftc_prod&dc=5047&query=amazon.com&sort_by=r&tbs=m

So there are actually two bugs here:
* one in our construction of the filter links for docs
* one preventing the time filter params from being used in collection searches.

**Comment by viclim** [comment]
@nickmarden
 I will take a look at this during this weekend.
