### ISSUE TITLE
fix flakey cucumber test: "Add/edit/remove Collection"

### ISSUE THREAD

**Issue by nickmarden** [GSA/search-gov#31]
The "Add/edit/remove Collection" cucumber test in `features/admin_center_manage_content.feature` is failing intermittently on CircleCI. Example:
https://circleci.com/gh/GSA/search-gov/250

```
(::) failed steps (::)

expected to find text "You have removed News and Blog from this site" in "Skip to Main Content Search.gov Select a site Select a site Add Site Send an Idea Need Help? john@agency.gov Display Name: agency site (agency.gov) Set as my default site Send me today's snapshot as a daily email Stop filtering bot traffic Dashboard Analytics Content Display Preview Activate Manage Content Content Overview Domains Collections Best Bets: Text Best Bets: Graphics Routed Queries RSS YouTube Twitter Flickr CollectionsAdd Collection News and Blog Preview Edit" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/web_steps.rb:112:in `/^(?:|I )should see "([^"]*)"$/'
./features/support/hooks.rb:8:in `block (2 levels) in <top (required)>'
./features/support/hooks.rb:7:in `block in <top (required)>'
features/admin_center_manage_content.feature:263:in `Then I should see "You have removed News and Blog from this site"'

Failing Scenarios:
cucumber features/admin_center_manage_content.feature:229 # Scenario: Add/edit/remove Collection
```

IIRC I did some investigating of the root cause of this error and it's related to the confirmation modal (something like "are you sure you want to remove this collection?") not being discoverable in the DOM by the Capybara driver...because it simply didn't exist. I think the root cause is that the "click" on the "Delete" button doesn't register with the headless browser.

I have since lost the captured screenshot that proves this, but it's easy to reproduce using the [capybara-screenshot](https://github.com/mattheworiordan/capybara-screenshot) gem.

**Comment by MothOnMars** [comment]
Some debugging tools that may be help:
```ruby
#features/step_definitions/debugging_steps.rb

Then /^show me the page$/ do
  save_and_open_page
end

Then /^show me the console$/ do
  binding.pry
end

# e.g., And I write the page body to /tmp/test-results/look_for_this_file_in_the_artifacts_tab_in_circleci.html
When /^I write the page body to (.*)$/ do |path|
  File.open(path, 'w') { |f| f.puts(page.body) }
end

#features/step_definitions/web_steps.rb

Then "I wait for ajax"  do #make sure any ajax is done running
  Timeout.timeout(Capybara.default_wait_time) do
    loop do
      active = page.evaluate_script('jQuery.active')
      break if active == 0
    end
  end
end
```

The following commits fixed a couple of similarly flakey Cuke tests (these may or may not be remotely helpful in this case):
https://github.com/GSA/search-gov/commit/d7d59eb54
https://github.com/GSA/search-gov/commit/a7c2b1e38

**Comment by MothOnMars** [comment]
Resolved by: https://github.com/GSA/search-gov/pull/87
