### ISSUE TITLE
set up parallel builds on CircleCI

### ISSUE THREAD

**Issue by MothOnMars** [GSA/search-gov#55]
As a search-gov developer,
I would like my tests to run in parallel on CircleCI
so that I get my test results faster.

The search-gov repo can support up to 8 parallel jobs. See https://circleci.com/docs/2.0/configuration-reference/#parallelism.

This story depends on https://github.com/GSA/search-gov/issues/59.

**Comment by nickmarden** [comment]
@MothOnMars can this be done by an open-source contributor?

**Comment by MothOnMars** [comment]
@nickmarden , I believe so, because all the configuration changes would happen in `.circleci/config.yml`. The internal settings for the repo already allow up to 8x parallelism. Per the docs, "If your repository is public, your CircleCI project will also be publicly available." 

https://circleci.com/docs/2.0/oss/

**Comment by nickmarden** [comment]
Great, thanks for doing the homework to answer that for me. I wonder if @HalahAb would be interested in looking at this one...

**Comment by MothOnMars** [comment]
Resolved by https://github.com/GSA/search-gov/pull/71.
