### ISSUE TITLE
create sitemaps model

### ISSUE THREAD

**Issue by MothOnMars** [GSA/search-gov#77]
We need a standard ActiveRecord model for a new Sitemap class. A sitemap should:
- belong to `:searchgov_domain` (which can have many sitemaps)
- have a non-null, `varchar(2000)` `url` database column
  - the `url` should be unique
  - the `url` should be read-only
- have a nullable `varchar(255)` last_crawl_status column
- have a nullable `datetime` last_crawled_at column
- determine the `searchgov_domain` it belongs to at the time of creation (see SearchgovUrl#set_searchgov_domain)
- mix in the `Fetchable` module, which includes additional validations

The spec should include the line `it_should_behave_like 'a record with a fetchable url'` to include the default `Fetchable` tests. This class has a lot in common with the other `Fetchable` classes: `IndexedDocument` and `SearchgovUrl`. Those classes and their specs may be helpful. Try to use [Shoulda's simple one-line matchers](http://matchers.shoulda.io/docs/v2.8.0/) for standard tests such as validations, etc.

**Comment by MothOnMars** [comment]
@ethanewing , here's the next story for you. Please let me know if you have questions.

**Comment by ethanewing** [comment]
Will do!

**Comment by MothOnMars** [comment]
Resolved by https://github.com/GSA/search-gov/pull/92
