### ISSUE TITLE
Super Admins should be able to add and view sitemaps for searchgov domains

### ISSUE THREAD

**Issue by MothOnMars** [GSA/search-gov#95]
As a super admin
I would like to be able to add and view sitemaps for a domain on the `admin/searchgov_domains` page
because sites don't always put their sitemaps in expected places (like `https://foo.gov/sitemap.xml`) and they don't always list their sitemap locations on their `robots.txt` file.

Google allows webmasters to submit a sitemap URL in the Google Search Console, so some customers expect that functionality.

To support this, we should add a "Show" link for each searchgov domain on the `admin/searchgov_domains` page. (See the `admin/affiliates` page and code for how that should look & function).  The "show" view for each searchgov domain should display the following info for that record:
- domain
- status
- urls_count
- unfetched_urls_count
- created_at
- updated_at

It should also include a sub-table that displays the sitemaps. For now, the display should only include the URL and created_at/updated_at columns. The super admin should be able to add a new sitemap url. An example of how that might work is the "Excluded domains" section for Affiliates (`admin/affiliates` > Edit > Settings):
![image](https://user-images.githubusercontent.com/437455/41800324-e58c0acc-7629-11e8-81cc-89190e0c7a2a.png)
I'm actually not sure if you can put an editable table within the "Show" view of an active scaffold record; it may need to be in an "Edit" view, but either way we need to ensure that the other searchgov domain values are not editable. 

[ActiveScaffold](https://github.com/activescaffold/active_scaffold) is the gem used for the super admin views. Its documentation leaves something to be desired, but our own super admin code can be very helpful for reverse-engineering, and there are some how-to's out there on the web.

Because the automagic nature of the active scaffold code makes it difficult to test, this should be tested with a cucumber feature in `features/admin.feature`.

**Comment by dawnpm** [comment]
`Show` and `Edit` are separate on all the other pages. There's not, so far, been an option to edit from within a `Show` display.

**Comment by MothOnMars** [comment]
https://www.pivotaltracker.com/n/projects/24228/stories/158609454
