### ISSUE TITLE
replace poltergeist with headless Chrome in Cucumber tests

### ISSUE THREAD

**Issue by MothOnMars** [GSA/search-gov#99]
As a developer
I would like our cucumber suite to use headless Chrome instead of poltergeist
because poltergeist is a PhantomJS driver
and PhantomJS was [abandoned in April 2017](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE).

Note: This story might also be a good point to upgrade to Capybara 3.X.

**Comment by dawnpm** [comment]
resolved by https://github.com/GSA/search-gov/pull/869
